---

- name: Check if repositorio binary exists
  stat: path=/usr/local/bin/repositorio
  register: st
  tags: repositorio

- name: Install wget
  yum: name=wget state=present
  tags: repositorio

- name: Install Repositorio
  shell: wget -O - http://get.repositor.io/ | bash
  when: not st.stat.exists
  tags: repositorio

- name: Template repositorio.conf
  template: src=repositorio.conf.j2 dest=/etc/rex/repositorio.conf owner=root group=root mode=0644
  tags: repositorio

- name: Configure cron
  cron: name="update mirrors" minute="0" hour="*/8" job="/usr/local/bin/repositorio --mirror --update-metadata --repo=all"
  tags: repositorio

- name: Template nginx conf
  template: src=repositorio-nginx.conf.j2 dest=/etc/nginx/conf.d/repositorio.conf owner=root group=root mode=0644
  notify: restart nginx
  tags: repositorio

- name: Fix selinux permissions
  command: chcon -Rt httpd_sys_content_t /var/www/html
  when: selinux is defined and selinux
  tags: repositorio
